annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Helm chart versioning will now follow the SonarQube product versioning"
    - kind: changed
      description: "Update SonarQube to 10.0.0"
    - kind: fixed
      description: "Make jvmOpts and jvmCeOpts not override env vars and sonar properties"
    - kind: added
      description: "Add helm-chart-sonarqube as chart source"
    - kind: fixed
      description: "Fixed unsupported wget parameter --proxy off with --no-proxy"
    - kind: fixed
      description: "Fix install_plugins.sh not deleting previously installed plugins"
    - kind: added
      description: "Support for extraVolumes and extraVolumeMounts in sonar pods"
    - kind: changed
      description: "Clarify doc for custom cacert secret"
    - kind: changed
      description: "Refactor Deployment manifest to match the Statefulset manifest"
    - kind: added
      description: "Add a configurable Prometheus PodMonitor resource"
    - kind: changed
      description: "Prometheus exporter updated to 0.17.2"
    - kind: changed
      description: "Allow setting priorityClassName for StatefulSets"
    - kind: changed
      description: "Adds timeoutSeconds parameter to probes"
    - kind: changed
      description: "Update SonarQube logo"
    - kind: changed
      description: "Bootstrap chart version 9.x.x dedicated to the future SonarQube 10.0"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: sonarqube
      image: sonarqube:10.0.0-community
  artifacthub.io/links: |
    - name: support
      url: https://community.sonarsource.com/
    - name: Chart Source
      url: https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
apiVersion: v2
appVersion: 10.0.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  version: 10.15.0
- condition: nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.0.13
description: SonarQube offers Code Quality and Code Security analysis for up to 27
  languages. Find Bugs, Vulnerabilities, Security Hotspots and Code Smells throughout
  your workflow.
home: https://www.sonarqube.org/
icon: https://raw.githubusercontent.com/SonarSource/sonarqube-static-resources/master/helm/SonarQubeLogo.svg
keywords:
- coverage
- security
- code
- quality
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: leo.geoffroy+helm@sonarsource.com
  name: leo-geoffroy-sonarsource
- email: carmine.vassallo@sonarsource.com
  name: carminevassallo
- email: jeremy.cotineau@sonarsource.com
  name: jCOTINEAU
name: sonarqube
sources:
- https://github.com/SonarSource/helm-chart-sonarqube
- https://github.com/SonarSource/docker-sonarqube
- https://github.com/SonarSource/sonarqube
type: application
version: 10.0.0+521
