version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    networks:
      - jenkins_network
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JENKINS_SLAVE_AGENT_PORT=50000
    user: "0:0"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    networks:
      - jenkins_network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

networks:
  jenkins_network:
    name: jenkins_network

volumes:
  jenkins_home:
