---
- name: Deploy Apache Server
  hosts: group_a
  become: yes
  tasks:
    - name: Apache
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: enable Apache
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes